version: "3.3"

services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    restart: "always"
    ports:
      - "3001:3000"
    volumes:
      - "./front-end:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - backend

networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge
