version: "3.3"

services:
  web:
    image: nginx:latest
    container_name: web
    restart: "always"
    ports:
      - 80:80
    volumes:
      - ./front-end/nginx.conf:/etc/nginx/nginx.conf
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    restart: "always"
    expose:
      - 3000
    volumes:
      - "./front-end:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
