version: "3.3"

services:
  web:
    image: nginx:latest
    container_name: web
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/var/jenkins_home/workspace/codeback/web/nginx.conf
    networks:
      - backend
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    restart: "always"
    ports:
      - "3000:3000"
    volumes:
      - "./front-end:/var/jenkins_home/workspace/codeback/front-end"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - backend
networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge
